### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by BognarB** [0-1-0/lightblue-0.4#5]
Hi Guys,

After install lightblue i got this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lightblue/**init**.py", line 160, in <module>
    from _lightblue import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lightblue/_lightblue.py", line 297, in <module>
    class _SDPQueryRunner(Foundation.NSObject):
objc.error: _SDPQueryRunner is overriding existing Objective-C class

any ideia?

**Comment by aodock** [comment]
i get different error,..
```
In [1]: import lightblue
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_bridgesupport.py:643: RuntimeWarning: Error parsing BridgeSupport data for IOBluetooth: PyObjCRT_SkipTypeSpec: Got '0x29' at end of union encoding, expecting '0x29'
  warnings.warn("Error parsing BridgeSupport data for %s: %s" % (frameworkName, e), RuntimeWarning)
```

**Comment by gmsanchez** [comment]
@aodock, I think the error you get has to do with this: https://bitbucket.org/ronaldoussoren/pyobjc/issue/111/cant-import-lightblue-with-macport-or

**Comment by aodock** [comment]
@gmsanchez , Thank you. Actually it took a while to figure out what was been said exactly in that link,.. Finally [this](https://bitbucket.org/ronaldoussoren/pyobjc/downloads) did helped.
